=== pmarches/bitcoop/xslt/bcoop.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="fileMatchType">
        <xs:attribute name="pattern" type="xs:string" use="required"/>
        <xs:attribute name="size" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="execType" >
        <xs:attribute name="cmd" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="envType">
        <xs:attribute name="var" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="dataType">
        <xs:choice>
            <xs:element name="include" type="fileMatchType" maxOccurs="unbounded" minOccurs="0" />
            <xs:element name="exclude" type="fileMatchType" maxOccurs="unbounded" minOccurs="0" />
            <xs:element name="env" type="envType" maxOccurs="unbounded" minOccurs="0" />
            <xs:element name="exec" type="execType" maxOccurs="unbounded" minOccurs="0" />
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="scheduleMatchType" >
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="scheduleType">
        <xs:sequence>
            <xs:element name="year" type="scheduleMatchType"  maxOccurs="1" minOccurs="0"/>
            <xs:element name="month" type="scheduleMatchType"  maxOccurs="1" minOccurs="0"/>
            <xs:element name="weekday" type="scheduleMatchType"  maxOccurs="1" minOccurs="0"/>
            <xs:element name="day" type="scheduleMatchType"  maxOccurs="1" minOccurs="0"/>
            <xs:element name="hour" type="scheduleMatchType"  maxOccurs="1" minOccurs="0"/>
            <xs:element name="minute" type="scheduleMatchType"  maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>


    <xs:complexType name="refType" >
        <xs:attribute name="ref" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="jobType">
        <xs:sequence>
            <xs:element name="schedule" type="refType" />
            <xs:element name="data" type="refType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="jobsType">
        <xs:sequence>
            <xs:element name="job" type="jobType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="backupConfigType">
        <xs:sequence>
            <xs:element name="data" type="dataType" maxOccurs="unbounded" minOccurs="0" />
            <xs:element name="schedule" type="scheduleType"  maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="jobs" type="jobsType"  maxOccurs="1" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bcoopType">
        <xs:choice>
            <xs:element name="backupConfig" type="backupConfigType" />
        </xs:choice>
    </xs:complexType>
    
    <xs:element name="bcoop" type="bcoopType" />
</xs:schema>

=== pmarches/bitcoop/xslt/sampleData.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="mainSS.xml"?>

<bcoop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bcoop.xsd">
    <backupConfig>
        <data name="criticalFiles">
            <env var="soniaDbDump" value="/tmp/soniaDb.sql" />
            <exec cmd="mysqldump sonia -usonia -Pdauphin >${soniaDbDump}" />
            <!--include pattern="${soniaDbDump}" / -->
            <include pattern="/tmp/.*" />
        </data>
        
        <data name="sampleFiles">
            <include pattern="/home/pmarches/workspace/bcoop/testData/filesToBackup/.*" />
        </data>
        
        <schedule name="daily dawn">
            <year value="*"/>
            <month value="*"/>
            <weekday value="*"/>
            <day value="*"/>
            <hour value="04"/>
            <minute value="00"/>
        </schedule>
        
        <jobs>
            <job>
                <schedule ref="daily dawn" />
                <data ref="criticalFiles" />
            </job>
            <job>
                <schedule ref="bootime" />
                <data ref="sampleFiles" />
            </job>
        </jobs>
        
    </backupConfig>

</bcoop>
